service: click-stats
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-1'}
  httpApi:
    cors: true
  logs:
    restApi: true
  environment:
    STAGE: ${opt:stage, 'dev'}
    TABLE_NAME: click_events_table_${opt:stage, 'dev'}

custom:
  clickEventsTable: arn:aws:dynamodb:${self:provider.region}:*:table/click_events_table_${opt:stage, 'dev'}


package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  recordClick:
    handler: bin/clickEventHandler
    events:
      - httpApi:
          path: /click-event
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: ${self:custom.clickEventsTable}

resources:
  Resources:
    clickEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: click_events_table_${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: record_type
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
          - AttributeName: shape
            AttributeType: S
          - AttributeName: color
            AttributeType: S
          - AttributeName: quadrant
            AttributeType: S
        KeySchema:
          - AttributeName: record_type
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        #  This allows efficient access of shape, color, or quadrant specific stats 
        GlobalSecondaryIndexes:
          - IndexName: shapeEvents
            KeySchema:
              - AttributeName: shape
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL
          - IndexName: colorEvents
            KeySchema:
              - AttributeName: color
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL
          - IndexName: quadrantEvents
            KeySchema:
              - AttributeName: quadrant
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-iam-roles-per-function
