service: click-stats
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

  stage: dev
  region: us-west-1

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  recordClick:
    handler: bin/clickHandler
    events:
      - httpApi:
          path: /clickHandler
          method: post
