service: click-stats
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

  stage: dev
  region: us-west-1

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  recordClick:
    handler: bin/clickEventHandler
    events:
      - httpApi:
          path: /click-event
          method: post

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: clickEvents
        AttributeDefinitions:
          - AttributeName: record_type
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
          - AttributeName: shape
            AttributeType: S
          - AttributeName: color
            AttributeType: S
          - AttributeName: quadrant
            AttributeType: S
        KeySchema:
          - AttributeName: event_type
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        #  This allows efficient access of shape, color, or quadrant specific stats 
        GlobalSecondaryIndexes:
          - IndexName: shapeEvents
            KeySchema:
              - AttributeName: shape
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL
          - IndexName: colorEvents
            KeySchema:
              - AttributeName: color
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL
          - IndexName: quadrantEvents
            KeySchema:
              - AttributeName: quadrant
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
